name: Build Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE: test-image

jobs:
  setup-build-publish-deploy:
    name: Builds docker images then throws it away
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$IMAGE:$GITHUB_SHA" \
          .
